server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: ia-task-configuration
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
